name: Release

on:
  workflow_dispatch:
  push:
#    paths:
#      - 'pom.xml'
#      - '**/pom.xml'
#      - '.mvn/**'
#      - '.github/workflows/**'
#      - 'src/main/**'
#      - 'src/test/**'
    branches:
      - 'master'

permissions:
  contents: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update settings.xml
        uses: s4u/maven-settings-action@v2
        with:
          servers: |
            [
              {
                "id": "ossrh",
                "username": "${{ secrets.MAVEN_CENTRAL_USERNAME }}",
                "password": "${{ secrets.MAVEN_CENTRAL_PASSWORD }}"
              }
            ]

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalação do JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven

      - name: Verify with Maven
        run: mvn -T 1C -B package

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

